### ISSUE TITLE
How do you get onselect working?

### ISSUE THREAD

**Issue by pufamuf** [emposha/FCBKcomplete#100]
I did a simple
onselect: alert("Thanks for visiting!"), and
onremove: alert("Thanks for visiting!"),

and the dialog appears on page load, never when you add or remove an item :/ I want to add a php code in there and it doesn't work at all after that.

**Comment by go2shibu** [comment]
Hi,
I want to change the text when click the item from the list and place the changed text into the text box.  I override the onselect method, but I noticed that selected text has been placed before fired onselect event. Could you please gimme the solution to call function before the selected item place in the text box?
