### ISSUE TITLE
Demo page?

### ISSUE THREAD

**Issue by TimoSolo** [emposha/FCBKcomplete#150]
Hi, would be nice to have a demo page (github page) so it can be tested before downloading.

**Comment by emposha** [comment]
Hi Timo, this plugin not supported anymore...
Please use https://select2.github.io/

**Comment by TimoSolo** [comment]
awesome. Maybe update the Readme to avoid confusion

**Comment by emposha** [comment]
done

**Comment by TimoSolo** [comment]
![Image of gangnamtocat](https://octodex.github.com/images/gangnamtocat.png)
